### ISSUE TITLE
I found the wrong parts maybe in your docs with markdown syntax!

### ISSUE THREAD

**Issue by JH9892** [upswp/upswp.github.io#1]
## Motivation

I found something written incorrectly in the paragraph. It may be necessary to check whether the'Experience' paragraph belongs to the 'Current Interest' paragraph.  

## Suggestion

In my opinion, proper white spaces and line breaks will help your docs.  
It refers to the highlighted area as shown in the picture below. Please check :)
![pr01](https://user-images.githubusercontent.com/32566767/104127583-3c85a480-53a6-11eb-9228-8d3102999540.PNG)

**Comment by upswp** [comment]
Thanks! I got it!
